In [1]:
import pandas as pd
import matplotlib.pyplot as plt

import os

In [2]:
os.listdir('./Desktop/g20/')

['API_ARG_DS2_en_csv_v2_3470307',
 'API_AUS_DS2_en_csv_v2_3475762',
 'API_BRA_DS2_en_csv_v2_3469779',
 'API_CAN_DS2_en_csv_v2_3471277',
 'API_CHN_DS2_en_csv_v2_3475488',
 'API_DEU_DS2_en_csv_v2_3483614',
 'API_ESP_DS2_en_csv_v2_3483073',
 'API_FRA_DS2_en_csv_v2_3484402',
 'API_GBR_DS2_en_csv_v2_3476694',
 'API_IDN_DS2_en_csv_v2_3469232',
 'API_IND_DS2_en_csv_v2_3469035',
 'API_ITA_DS2_en_csv_v2_3472313',
 'API_JPN_DS2_en_csv_v2_3482162',
 'API_KOR_DS2_en_csv_v2_3490177',
 'API_MEX_DS2_en_csv_v2_3471585',
 'API_RUS_DS2_en_csv_v2_3482760',
 'API_SAU_DS2_en_csv_v2_3480817',
 'API_TUR_DS2_en_csv_v2_3480375',
 'API_USA_DS2_en_csv_v2_3471341',
 'API_ZAF_DS2_en_csv_v2_3475392',
 'modified']

In [87]:
df_arg = pd.read_csv('./Desktop/g20/API_ARG_DS2_en_csv_v2_3470307/API_ARG_DS2_en_csv_v2_3470307.csv')
df_aus = pd.read_csv('./Desktop/g20/API_AUS_DS2_en_csv_v2_3475762/API_AUS_DS2_en_csv_v2_3475762.csv')
df_bra = pd.read_csv('./Desktop/g20/API_BRA_DS2_en_csv_v2_3469779/API_BRA_DS2_en_csv_v2_3469779.csv')
df_can = pd.read_csv('./Desktop/g20/API_CAN_DS2_en_csv_v2_3471277/API_CAN_DS2_en_csv_v2_3471277.csv')
df_chn = pd.read_csv('./Desktop/g20/API_CHN_DS2_en_csv_v2_3475488/API_CHN_DS2_en_csv_v2_3475488.csv')
df_deu = pd.read_csv('./Desktop/g20/API_DEU_DS2_en_csv_v2_3483614/API_DEU_DS2_en_csv_v2_3483614.csv')
df_esp = pd.read_csv('./Desktop/g20/API_ESP_DS2_en_csv_v2_3483073/API_ESP_DS2_en_csv_v2_3483073.csv')
df_fra = pd.read_csv('./Desktop/g20/API_FRA_DS2_en_csv_v2_3484402/API_FRA_DS2_en_csv_v2_3484402.csv')
df_gbr = pd.read_csv('./Desktop/g20/API_GBR_DS2_en_csv_v2_3476694/API_GBR_DS2_en_csv_v2_3476694.csv')
df_idn = pd.read_csv('./Desktop/g20/API_IDN_DS2_en_csv_v2_3469232/API_IDN_DS2_en_csv_v2_3469232.csv')
df_ind = pd.read_csv('./Desktop/g20/API_IND_DS2_en_csv_v2_3469035/API_IND_DS2_en_csv_v2_3469035.csv')
df_ita = pd.read_csv('./Desktop/g20/API_ITA_DS2_en_csv_v2_3472313/API_ITA_DS2_en_csv_v2_3472313.csv')
df_jpn = pd.read_csv('./Desktop/g20/API_JPN_DS2_en_csv_v2_3482162/API_JPN_DS2_en_csv_v2_3482162.csv')
df_kor = pd.read_csv('./Desktop/g20/API_KOR_DS2_en_csv_v2_3490177/API_KOR_DS2_en_csv_v2_3490177.csv')
df_mex = pd.read_csv('./Desktop/g20/API_MEX_DS2_en_csv_v2_3471585/API_MEX_DS2_en_csv_v2_3471585.csv')
df_rus = pd.read_csv('./Desktop/g20/API_RUS_DS2_en_csv_v2_3482760/API_RUS_DS2_en_csv_v2_3482760.csv')
df_sau = pd.read_csv('./Desktop/g20/API_SAU_DS2_en_csv_v2_3480817/API_SAU_DS2_en_csv_v2_3480817.csv')
df_tur = pd.read_csv('./Desktop/g20/API_TUR_DS2_en_csv_v2_3480375/API_TUR_DS2_en_csv_v2_3480375.csv')
df_usa = pd.read_csv('./Desktop/g20/API_USA_DS2_en_csv_v2_3471341/API_USA_DS2_en_csv_v2_3471341.csv')
df_zaf = pd.read_csv('./Desktop/g20/API_ZAF_DS2_en_csv_v2_3475392/API_ZAF_DS2_en_csv_v2_3475392.csv')

In [88]:
columns_to_keep = ['Rural population (% of total population)', 'Population growth (annual %)','Fertility rate, total (births per woman)', 'Unemployment, female (% of female labor force) (national estimate)', 'Unemployment, youth male (% of male labor force ages 15-24) (national estimate)', 'Ratio of female to male labor force participation rate (%) (national estimate)', 'GDP per person employed (constant 2017 PPP $)', 'Employment in agriculture (% of total employment) (modeled ILO estimate)', 'Income share held by highest 20%', 'GDP growth (annual %)', 'Inflation, GDP deflator (annual %)', 'Age dependency ratio (% of working-age population)', 'Life expectancy at birth, female (years)', 'Individuals using the Internet (% of population)', 'Electric power consumption (kWh per capita)', 'Population, female', 'Unemployment, total (% of total labor force) (national estimate)', 'Literacy rate, youth total (% of people ages 15-24)']

df_list = [df_arg, df_bra, df_can, df_chn, df_deu, df_esp, df_fra, df_gbr, df_idn, df_ind, df_ita, df_jpn, df_kor, df_mex, df_rus, df_sau, df_tur, df_usa, df_zaf]

df_names_list = ['df_arg', 'df_bra', 'df_can', 'df_chn', 'df_deu', 'df_esp', 'df_fra', 'df_gbr', 'df_idn', 'df_ind', 'df_ita', 'df_jpn', 'df_kor', 'df_mex', 'df_rus', 'df_sau', 'df_tur', 'df_usa', 'df_zaf']

In [89]:
a = 0
for df_ in df_list:    
    df = df_.drop(['Country Name', 'Country Code'], axis=1)
    df = df.rename(columns={"Indicator Name": "Year"}, errors="raise")
    df = df.drop(['Indicator Code'], axis=1)
    df = df.set_index('Year').T
    df = df[columns_to_keep]
    df.to_csv("./Desktop/g20/modified/{}.csv".format(df_names_list[a]))
    print("Saved to ./Desktop/g20/modified/{}.csv".format(df_names_list[a]))
    a += 1

./Desktop/g20/modified/df_arg.csv
./Desktop/g20/modified/df_bra.csv
./Desktop/g20/modified/df_can.csv
./Desktop/g20/modified/df_chn.csv
./Desktop/g20/modified/df_deu.csv
./Desktop/g20/modified/df_esp.csv
./Desktop/g20/modified/df_fra.csv
./Desktop/g20/modified/df_gbr.csv
./Desktop/g20/modified/df_idn.csv
./Desktop/g20/modified/df_ind.csv
./Desktop/g20/modified/df_ita.csv
./Desktop/g20/modified/df_jpn.csv
./Desktop/g20/modified/df_kor.csv
./Desktop/g20/modified/df_mex.csv
./Desktop/g20/modified/df_rus.csv
./Desktop/g20/modified/df_sau.csv
./Desktop/g20/modified/df_tur.csv
./Desktop/g20/modified/df_usa.csv
./Desktop/g20/modified/df_zaf.csv

In [91]:
df_arg = pd.read_csv('./Desktop/g20/modified/df_arg.csv')
#df_aus = pd.read_csv('./Desktop/g20/modified/df_aus.csv')
df_bra = pd.read_csv('./Desktop/g20/modified/df_bra.csv')
df_can = pd.read_csv('./Desktop/g20/modified/df_can.csv')
df_chn = pd.read_csv('./Desktop/g20/modified/df_chn.csv')
df_deu = pd.read_csv('./Desktop/g20/modified/df_deu.csv')
df_esp = pd.read_csv('./Desktop/g20/modified/df_esp.csv')
df_fra = pd.read_csv('./Desktop/g20/modified/df_fra.csv')
df_gbr = pd.read_csv('./Desktop/g20/modified/df_gbr.csv')
df_idn = pd.read_csv('./Desktop/g20/modified/df_idn.csv')
df_ind = pd.read_csv('./Desktop/g20/modified/df_ind.csv')
df_ita = pd.read_csv('./Desktop/g20/modified/df_ita.csv')
df_jpn = pd.read_csv('./Desktop/g20/modified/df_jpn.csv')
df_kor = pd.read_csv('./Desktop/g20/modified/df_kor.csv')
df_mex = pd.read_csv('./Desktop/g20/modified/df_mex.csv')
df_rus = pd.read_csv('./Desktop/g20/modified/df_rus.csv')
df_sau = pd.read_csv('./Desktop/g20/modified/df_sau.csv')
df_tur = pd.read_csv('./Desktop/g20/modified/df_tur.csv')
df_usa = pd.read_csv('./Desktop/g20/modified/df_usa.csv')
df_zaf = pd.read_csv('./Desktop/g20/modified/df_zaf.csv')

In [92]:
df_arg.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_bra.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_can.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_chn.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_deu.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_esp.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_fra.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_gbr.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_idn.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_ind.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_ita.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_jpn.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_kor.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_mex.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_rus.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_sau.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_tur.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_usa.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)
df_zaf.rename(columns={'Unnamed: 0': 'Year'}, inplace=True)

In [98]:
df_arg.head()

,Year,Rural population (% of total population),Population growth (annual %),"Fertility rate, total (births per woman)","Unemployment, female (% of female labor force) (national estimate)","Unemployment, youth male (% of male labor force ages 15-24) (national estimate)",Ratio of female to male labor force participation rate (%) (national estimate),GDP per person employed (constant 2017 PPP $),Employment in agriculture (% of total employment) (modeled ILO estimate),Income share held by highest 20%,GDP growth (annual %),"Inflation, GDP deflator (annual %)",Age dependency ratio (% of working-age population),"Life expectancy at birth, female (years)",Individuals using the Internet (% of population),Electric power consumption (kWh per capita),"Population, female","Unemployment, total (% of total labor force) (national estimate)","Literacy rate, youth total (% of people ages 15-24)"
0,1960,26.389,NaN,3.109,NaN,NaN,27.559616,NaN,NaN,NaN,NaN,NaN,57.683949,68.154,NaN,NaN,10150763.0,NaN,NaN
1,1961,25.783,1.624717,3.100,NaN,NaN,NaN,NaN,NaN,NaN,5.427843,20.310698,57.785747,68.362,NaN,NaN,10327991.0,NaN,NaN
2,1962,25.233,1.600079,3.090,NaN,NaN,NaN,NaN,NaN,NaN,-0.852022,28.871842,57.746993,68.536,NaN,NaN,10506338.0,NaN,NaN
3,1963,24.691,1.575354,3.079,NaN,NaN,NaN,NaN,NaN,NaN,-5.308197,25.591154,57.609929,68.685,NaN,NaN,10685346.0,NaN,NaN
4,1964,24.156,1.549258,3.068,NaN,NaN,NaN,NaN,NaN,NaN,10.130298,28.774617,57.437942,68.820,NaN,NaN,10864242.0,NaN,NaN

In [96]:
df_gbr.head()

,Year,Rural population (% of total population),Population growth (annual %),"Fertility rate, total (births per woman)","Unemployment, female (% of female labor force) (national estimate)","Unemployment, youth male (% of male labor force ages 15-24) (national estimate)",Ratio of female to male labor force participation rate (%) (national estimate),GDP per person employed (constant 2017 PPP $),Employment in agriculture (% of total employment) (modeled ILO estimate),Income share held by highest 20%,GDP growth (annual %),"Inflation, GDP deflator (annual %)",Age dependency ratio (% of working-age population),"Life expectancy at birth, female (years)",Individuals using the Internet (% of population),Electric power consumption (kWh per capita),"Population, female","Unemployment, total (% of total labor force) (national estimate)","Literacy rate, youth total (% of people ages 15-24)"
0,1960,21.556,NaN,2.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.664141,74.2,NaN,2412.137405,27094990.0,NaN,NaN
1,1961,21.626,0.760460,2.78,NaN,NaN,43.238578,NaN,NaN,NaN,2.677119,3.387796,54.215750,73.9,NaN,2553.693182,27277700.0,NaN,NaN
2,1962,21.763,0.848661,2.86,NaN,NaN,NaN,NaN,NaN,NaN,1.102910,3.369205,54.431065,74.0,NaN,2780.657277,27484998.0,NaN,NaN
3,1963,21.901,0.748366,2.88,NaN,NaN,NaN,NaN,NaN,NaN,4.874384,1.589148,54.481651,73.9,NaN,3002.087605,27667276.0,NaN,NaN
4,1964,22.040,0.650258,2.93,NaN,NaN,NaN,NaN,NaN,NaN,5.533659,3.344812,54.643298,74.8,NaN,3127.462963,27827179.0,NaN,NaN

In [102]:
for i in range(len(df_names_list)):
    print("{}.csv".format(df_names_list[i]))

df_arg.csv
df_bra.csv
df_can.csv
df_chn.csv
df_deu.csv
df_esp.csv
df_fra.csv
df_gbr.csv
df_idn.csv
df_ind.csv
df_ita.csv
df_jpn.csv
df_kor.csv
df_mex.csv
df_rus.csv
df_sau.csv
df_tur.csv
df_usa.csv
df_zaf.csv

In [103]:
modified_dfs = [df_arg, df_bra, df_can, df_chn, df_deu, df_esp, df_fra, df_gbr, df_idn, df_ind, df_ita, df_jpn, df_kor, df_mex, df_rus, df_sau, df_tur, df_usa, df_zaf]
a = 0
for df_ in modified_dfs:
    df_.to_csv("./Desktop/g20/modified/{}.csv".format(df_names_list[a]))
    print("Saved to ./Desktop/g20/modified/{}.csv".format(df_names_list[a]))
    a += 1

Saved to ./Desktop/g20/modified/df_arg.csv
Saved to ./Desktop/g20/modified/df_bra.csv
Saved to ./Desktop/g20/modified/df_can.csv
Saved to ./Desktop/g20/modified/df_chn.csv
Saved to ./Desktop/g20/modified/df_deu.csv
Saved to ./Desktop/g20/modified/df_esp.csv
Saved to ./Desktop/g20/modified/df_fra.csv
Saved to ./Desktop/g20/modified/df_gbr.csv
Saved to ./Desktop/g20/modified/df_idn.csv
Saved to ./Desktop/g20/modified/df_ind.csv
Saved to ./Desktop/g20/modified/df_ita.csv
Saved to ./Desktop/g20/modified/df_jpn.csv
Saved to ./Desktop/g20/modified/df_kor.csv
Saved to ./Desktop/g20/modified/df_mex.csv
Saved to ./Desktop/g20/modified/df_rus.csv
Saved to ./Desktop/g20/modified/df_sau.csv
Saved to ./Desktop/g20/modified/df_tur.csv
Saved to ./Desktop/g20/modified/df_usa.csv
Saved to ./Desktop/g20/modified/df_zaf.csv